apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-app.fullname" . }}
  labels:
    {{- include "platform-app.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "platform-app.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "platform-app.labels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "platform-app.serviceAccountName" . }}

      {{- $repo := required "image.repository is required" .Values.image.repository }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ $repo }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 5000

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
