kube-prometheus-stack:

  grafana:
    adminPassword: admin123
    service:
      type: LoadBalancer

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    enabled: true

  nodeExporter:
    enabled: true
