apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/techngi/platform-environments.git
    targetRevision: master
    path: helm/platform-app
    helm:
      valueFiles:
        - ../../envs/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
